### ISSUE TITLE
Project section not loading

### ISSUE THREAD

**Issue by azeebneuron** [charlesrocket/halve-z#31]
So i have cloned the repo and i am building the website using zola build and zola serve. Every part of the website is working fine except for the project/code section. I am attaching a screenshot.
![Screenshot from 2024-06-11 19-14-30](https://github.com/charlesrocket/halve-z/assets/137313478/66973de2-ad85-4eac-8bc7-8744087c338c)

**Comment by charlesrocket** [comment]
@azeebneuron `zola serve` will render placeholder cards to preserve API calls. There is no way to add custom flags (yet?) so I decided to use placeholders since live reload would burn thro API limits very fast. To preview the page locally, you could `zola build` and then serve the site with python/etc.
